[pytest]
asyncio_default_fixture_loop_scope = function
filterwarnings =
    ignore::DeprecationWarning:pytz.tzinfo
    ignore::DeprecationWarning:importlib._bootstrap
    ignore:ast.NameConstant is deprecated and will be removed in Python 3.14.*:DeprecationWarning
    ignore:distutils Version classes are deprecated. Use packaging.version instead..*:DeprecationWarning
